{% set name = "N2SNUserTools" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5612f1d0c31c1bd0c4f0c493236610b988291800d07862d5e6427aa162964468

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - n2sn_add_user = N2SNUserTools.cli:n2sn_add_user
    - n2sn_list_users = N2SNUserTools.cli:n2sn_list_users
    - n2sn_remove_user = N2SNUserTools.cli:n2sn_remove_user
    - n2sn_search_user = N2SNUserTools.cli:n2sn_search_user

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - krb5
    - ldap3
    - prettytable
    - python-gssapi
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - N2SNUserTools
    - N2SNUserTools.cli
    - N2SNUserTools.ldap
    - N2SNUserTools.unix
    - N2SNUserTools.utils

about:
  home: https://github.com/nsls-ii/N2SNUserTools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: User tools for the NSLS-II Science Network

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
